runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10

runtime_config:
  python_version: 3
